#line 2 "pplex.c"

#line 4 "pplex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer pp_create_buffer
#define yy_delete_buffer pp_delete_buffer
#define yy_flex_debug pp_flex_debug
#define yy_init_buffer pp_init_buffer
#define yy_flush_buffer pp_flush_buffer
#define yy_load_buffer_state pp_load_buffer_state
#define yy_switch_to_buffer pp_switch_to_buffer
#define yyin ppin
#define yyleng ppleng
#define yylex pplex
#define yylineno pplineno
#define yyout ppout
#define yyrestart pprestart
#define yytext pptext
#define yywrap ppwrap
#define yyalloc ppalloc
#define yyrealloc pprealloc
#define yyfree ppfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE pprestart(ppin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t ppleng;

extern FILE *ppin, *ppout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up pptext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up pptext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via pprestart()), so that the user can continue scanning by
	 * just pointing ppin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when pptext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t ppleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow ppwrap()'s to do buffer switches
 * instead of setting up a fresh ppin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void pprestart (FILE *input_file  );
void pp_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE pp_create_buffer (FILE *file,int size  );
void pp_delete_buffer (YY_BUFFER_STATE b  );
void pp_flush_buffer (YY_BUFFER_STATE b  );
void pppush_buffer_state (YY_BUFFER_STATE new_buffer  );
void pppop_buffer_state (void );

static void ppensure_buffer_stack (void );
static void pp_load_buffer_state (void );
static void pp_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER pp_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE pp_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE pp_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE pp_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *ppalloc (yy_size_t  );
void *pprealloc (void *,yy_size_t  );
void ppfree (void *  );

#define yy_new_buffer pp_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        ppensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pp_create_buffer(ppin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        ppensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pp_create_buffer(ppin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define ppwrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *ppin = (FILE *) 0, *ppout = (FILE *) 0;

typedef int yy_state_type;

extern int pplineno;

int pplineno = 1;

extern char *pptext;
#define yytext_ptr pptext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up pptext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	ppleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 52
#define YY_END_OF_BUFFER 53
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[224] =
    {   0,
        0,    0,    4,    4,    0,    0,    0,    0,   53,   51,
       43,   44,   51,   51,   46,   47,   51,   51,   51,   48,
       51,   48,   51,   48,   48,   48,   48,   48,   48,   48,
       48,   48,    4,    3,    4,   24,    8,    9,   24,   24,
       12,   13,   24,   24,   24,   21,   10,   21,   24,   24,
       21,   21,   21,   21,   21,   21,   21,   31,   25,   26,
       31,   31,   31,   31,   31,   28,   31,   28,   31,   31,
       28,   44,    0,   50,    0,    1,    0,   49,   43,   45,
       48,   48,   44,   48,   48,   48,   48,   48,   48,   48,
       48,   48,    4,    1,    9,    0,   23,    0,    0,   22,

        8,   21,   21,   11,   14,   15,   16,   21,   21,   21,
       26,    0,   30,    0,    0,   29,   25,   28,   28,   27,
        1,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,    1,   17,   21,   21,   21,   48,    5,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   21,   21,
       21,   48,   48,   39,   48,   48,   48,   48,   48,   48,
       40,   41,   42,   21,   21,   21,   32,   48,   48,   48,
       39,   48,   48,   48,   48,   48,   48,   40,   41,   42,
       21,   21,   21,   48,   48,   48,    6,   48,    2,   37,
        7,   48,   21,   21,   21,   48,   48,   48,   48,   38,

       19,   21,   18,   48,   48,   48,   48,   20,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   33,   36,
       35,   34,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    4,    1,    1,    1,    1,    5,    6,
        7,    8,    9,   10,   11,   12,    1,   13,   14,   15,
       16,   13,   13,   13,   13,   13,   13,    1,   17,    1,
       18,   19,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   36,   41,   36,   42,   36,
        1,    1,    1,    1,   36,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   36,   59,   60,   61,   62,   36,   63,   36,
       64,   36,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[238] =
    {   0,
        0,    0,   63,   64,   72,    0,  136,  155,  405,  960,
      960,  399,  384,  369,  960,  960,  339,  165,  180,  187,
      194,  201,   65,  179,  174,  208,  211,  214,  215,  175,
      220,  223,    0,  960,  338,  960,  960,  333,  331,  321,
      960,  960,  300,  245,  270,  277,  284,  291,   67,  290,
      226,  267,  300,  227,  301,  304,  305,  960,  960,  299,
      291,  283,  262,  308,  327,  334,  349,  356,  226,  260,
      239,  271,  265,  960,  263,    0,  363,  370,  960,  260,
      252,  377,  253,  342,  384,  385,  388,  389,  394,  397,
      398,  403,    0,    0,  247,  242,  960,  240,  446,  453,

      960,  315,  460,  960,  322,  343,  467,  413,  468,  471,
      237,  218,  960,  200,  472,  481,  960,  404,  495,  960,
        0,  489,  488,  507,  426,  492,  502,  510,  515,  526,
      530,  533,    0,  427,  538,  541,  549,  552,  435,  555,
      537,  563,  567,  573,  578,  592,  589,  607,  601,  596,
      617,  618,  624,  621,  635,  632,  640,  631,  658,  639,
      647,  654,  661,  673,  682,  681,  662,  685,  686,  696,
      960,  697,  700,  701,  713,  705,  706,  960,  960,  960,
      720,  728,  724,  725,  736,  737,  748,  754,  758,  759,
      765,  771,  775,  781,  780,  784,  788,  792,  793,  796,

      797,  800,  805,  810,  811,  817,  818,  831,  835,  840,
      848,  845,  852,  853,  861,  870,  873,  874,  878,  894,
      895,  898,  960,  926,  929,  932,  935,  195,  938,  941,
      944,  185,  947,  950,  173,  953,  956
    } ;

static yyconst flex_int16_t yy_def[238] =
    {   0,
      223,    1,  224,  224,  223,    5,  225,  225,  223,  223,
      223,  223,  226,  227,  223,  223,  223,  223,  223,  228,
      223,  228,  223,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  229,  223,  229,  223,  223,  223,  230,  231,
      223,  223,  223,  223,  223,  232,  223,  232,  223,  223,
      232,  232,  232,  232,  232,  232,  232,  223,  223,  223,
      233,  234,  223,  223,  223,  235,  223,  235,  223,  223,
      235,  223,  226,  223,  227,  236,  223,  223,  223,  223,
      228,  228,  223,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  229,  237,  223,  230,  223,  231,  223,  223,

      223,  232,  232,  223,  232,  232,  232,  232,  232,  232,
      223,  233,  223,  234,  223,  223,  223,  235,  235,  223,
      236,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  237,  232,  232,  232,  232,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  232,  232,
      232,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  232,  232,  232,  228,  228,  228,  228,
      223,  228,  228,  228,  228,  228,  228,  223,  223,  223,
      232,  232,  232,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  232,  232,  232,  228,  228,  228,  228,  228,

      232,  232,  232,  228,  228,  228,  228,  232,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,    0,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223
    } ;

static yyconst flex_int16_t yy_nxt[1025] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   22,   22,   22,   23,   10,   10,   24,
       25,   26,   27,   28,   25,   25,   25,   29,   25,   25,
       25,   25,   25,   25,   30,   25,   31,   32,   25,   25,
       25,   25,   24,   25,   26,   27,   28,   25,   25,   25,
       29,   25,   25,   25,   25,   25,   25,   30,   31,   32,
       25,   25,   25,   25,   34,   34,   79,   83,  101,   95,
       35,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   48,   48,   48,   49,   50,
       36,   51,   52,   51,   51,   51,   51,   51,   51,   53,

       51,   51,   51,   51,   51,   54,   55,   51,   56,   57,
       51,   51,   51,   51,   51,   52,   51,   51,   51,   51,
       51,   51,   53,   51,   51,   51,   51,   51,   54,   55,
       56,   57,   51,   51,   51,   51,   58,   59,   60,   61,
       62,   58,   58,   63,   64,   65,   66,   67,   68,   68,
       68,   68,   69,   70,   58,   58,   59,   60,   61,   62,
       58,   58,   63,   64,   65,   66,   67,   68,   68,   68,
       68,   69,   70,   58,   77,  118,   77,   78,   78,   78,
       78,   79,   80,  223,  223,  223,  223,  102,  223,   77,
      223,   77,   78,   78,   78,   78,   77,   81,   77,   82,

       82,   82,   82,   77,  113,   77,   78,   78,   78,   78,
       77,   89,   77,   82,   82,   82,   82,  223,   84,  223,
      223,  113,  223,  223,  223,  223,  223,  117,  111,  223,
       86,  223,  223,   89,  223,  223,  223,  223,  223,  111,
       84,   85,   87,   90,   97,   97,   91,   88,  223,   95,
      223,  107,   92,   86,   99,   83,   99,  100,  100,  100,
      100,  223,   80,  223,   85,   87,   90,   74,   74,   91,
       88,  101,   95,   72,  107,   92,  223,  120,  223,   99,
       76,   99,  100,  100,  100,  100,   99,  113,   99,  103,
      103,  103,  103,   99,  113,   99,  100,  100,  100,  100,

       99,  111,   99,  103,  103,  103,  103,  104,  105,  223,
      223,  223,  223,  223,  223,  223,  223,  115,   76,  115,
      116,  116,  116,  116,  223,   97,  223,  109,  117,  111,
      105,  223,  106,  223,   97,   95,  115,  108,  115,  116,
      116,  116,  116,  115,  110,  115,  119,  119,  119,  119,
      109,  223,  223,  223,  223,  106,   94,   76,  115,  108,
      115,  116,  116,  116,  116,  115,  110,  115,  119,  119,
      119,  119,   77,   74,   77,   78,   78,   78,   78,   77,
      122,   77,   78,   78,   78,   78,   77,   74,   77,   82,
       82,   82,   82,  223,  223,  223,  223,  223,  223,  223,

      223,   72,  122,  223,  223,  223,  223,  223,  223,  223,
      126,  125,  223,  223,  223,  223,  223,  223,  123,  131,
      223,  223,  223,  124,  223,  223,  127,  128,  129,  223,
      132,  130,  223,  126,  125,  223,  223,  223,  223,  223,
      135,  123,  131,  223,  223,  124,  223,  141,  127,  223,
      128,  129,  223,  132,  130,   99,  223,   99,  100,  100,
      100,  100,   99,  135,   99,  100,  100,  100,  100,   99,
      141,   99,  103,  103,  103,  103,  223,  223,  223,  223,
      223,  115,  223,  115,  116,  116,  116,  116,  223,  223,
      115,  134,  115,  116,  116,  116,  116,  223,  223,  223,

      223,  223,  136,  223,  115,  137,  115,  119,  119,  119,
      119,  223,  223,  223,  134,  138,  223,  223,  223,  223,
      223,  223,  142,  223,  223,  136,  223,  223,  137,  139,
      140,  144,  223,  223,  145,  223,  223,  223,  138,  223,
      143,  223,  223,  223,  223,  142,  223,  223,  223,  223,
      223,  139,  223,  140,  144,  223,  146,  145,  223,  223,
      223,  223,  143,  223,  223,  153,  223,  148,  223,  147,
      149,  150,  223,  223,  223,  154,  223,  223,  223,  146,
      223,  223,  223,  151,  223,  152,  156,  223,  223,  223,
      148,  147,  223,  149,  150,  223,  157,  154,  223,  223,

      223,  223,  155,  223,  223,  223,  151,  223,  152,  156,
      223,  159,  223,  223,  158,  165,  223,  223,  223,  157,
      161,  162,  163,  223,  155,  160,  223,  223,  223,  223,
      223,  223,  171,  223,  159,  223,  158,  223,  165,  164,
      223,  223,  223,  223,  223,  168,  223,  160,  223,  223,
      223,  223,  223,  166,  167,  169,  223,  172,  178,  223,
      175,  164,  173,  223,  170,  179,  177,  223,  168,  223,
      223,  223,  180,  223,  223,  166,  167,  174,  169,  176,
      172,  223,  223,  175,  223,  173,  170,  223,  223,  177,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  174,

      181,  223,  176,  182,  183,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  184,  185,
      187,  223,  223,  181,  223,  223,  182,  183,  191,  223,
      188,  223,  186,  223,  223,  223,  223,  223,  189,  223,
      223,  184,  185,  187,  192,  223,  223,  223,  223,  223,
      190,  191,  193,  188,  186,  194,  196,  223,  197,  223,
      189,  195,  223,  223,  198,  223,  192,  223,  223,  223,
      223,  223,  190,  199,  223,  193,  223,  223,  194,  196,
      223,  197,  223,  195,  223,  223,  223,  198,  223,  223,
      223,  223,  223,  223,  223,  223,  199,  223,  223,  223,

      201,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  200,  202,  223,  205,  223,  203,  204,  223,
      223,  223,  223,  201,  223,  208,  223,  223,  223,  223,
      206,  207,  223,  223,  200,  210,  202,  209,  205,  203,
      223,  204,  223,  223,  223,  212,  223,  223,  208,  223,
      223,  223,  206,  207,  223,  211,  223,  223,  210,  223,
      209,  223,  223,  223,  223,  213,  223,  214,  212,  223,
      223,  215,  223,  223,  223,  217,  218,  211,  216,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  213,  223,
      214,  223,  223,  219,  215,  221,  222,  223,  217,  218,

      223,  216,  220,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  219,  223,  221,  222,
      223,  223,  223,  223,  223,  220,   33,   33,   33,   71,
       71,   71,   73,  223,   73,   75,  223,   75,   93,  223,
       93,   96,  223,   96,   98,  223,   98,  112,  223,  112,
      114,  223,  114,  121,  223,  121,  133,  223,  133,    9,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,

      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223
    } ;

static yyconst flex_int16_t yy_chk[1025] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,   23,   23,   49,   49,
        3,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,   18,  235,   18,   18,   18,   18,
       18,   19,   19,   25,   30,   25,   30,  232,   24,   19,
       24,   19,   19,   19,   19,   19,   20,  228,   20,   20,

       20,   20,   20,   21,  114,   21,   21,   21,   21,   21,
       22,   30,   22,   22,   22,   22,   22,   26,   24,   26,
       27,  112,   27,   28,   29,   28,   29,   69,   69,   31,
       27,   31,   32,   30,   32,   51,   54,   51,   54,  111,
       24,   26,   28,   31,   98,   96,   32,   29,   71,   95,
       71,   54,   32,   27,   44,   83,   44,   44,   44,   44,
       44,   81,   80,   81,   26,   28,   31,   75,   73,   32,
       29,   45,   45,   72,   54,   32,   52,   70,   52,   45,
       63,   45,   45,   45,   45,   45,   46,   62,   46,   46,
       46,   46,   46,   47,   61,   47,   47,   47,   47,   47,

       48,   60,   48,   48,   48,   48,   48,   50,   52,   53,
       55,   53,   55,   56,   57,   56,   57,   64,   43,   64,
       64,   64,   64,   64,  102,   40,  102,   56,   65,   65,
       52,  105,   53,  105,   39,   38,   65,   55,   65,   65,
       65,   65,   65,   66,   57,   66,   66,   66,   66,   66,
       56,   84,  106,   84,  106,   53,   35,   17,   67,   55,
       67,   67,   67,   67,   67,   68,   57,   68,   68,   68,
       68,   68,   77,   14,   77,   77,   77,   77,   77,   78,
       84,   78,   78,   78,   78,   78,   82,   13,   82,   82,
       82,   82,   82,   85,   86,   85,   86,   87,   88,   87,

       88,   12,   84,   89,    9,   89,   90,   91,   90,   91,
       88,   87,   92,  118,   92,  118,    0,    0,   85,   91,
        0,    0,  108,   86,  108,    0,   88,   89,   90,    0,
       92,   90,    0,   88,   87,  125,  134,  125,  134,    0,
      108,   85,   91,    0,  139,   86,  139,  125,   88,    0,
       89,   90,    0,   92,   90,   99,    0,   99,   99,   99,
       99,   99,  100,  108,  100,  100,  100,  100,  100,  103,
      125,  103,  103,  103,  103,  103,  107,  109,  107,  109,
      110,  115,  110,  115,  115,  115,  115,  115,    0,    0,
      116,  107,  116,  116,  116,  116,  116,  123,  122,  123,

      122,  126,  109,  126,  119,  110,  119,  119,  119,  119,
      119,  127,    0,  127,  107,  122,  124,    0,  124,  128,
        0,  128,  126,    0,  129,  109,  129,    0,  110,  123,
      124,  128,    0,    0,  129,  130,    0,  130,  122,  131,
      127,  131,  132,    0,  132,  126,  141,  135,  141,  135,
      136,  123,  136,  124,  128,    0,  130,  129,  137,    0,
      137,  138,  127,  138,  140,  140,  140,  132,    0,  131,
      135,  136,  142,    0,  142,  141,  143,    0,  143,  130,
        0,    0,  144,  137,  144,  138,  143,  145,    0,  145,
      132,  131,    0,  135,  136,    0,  144,  141,  147,    0,

      147,  146,  142,  146,    0,  150,  137,  150,  138,  143,
      149,  146,  149,    0,  145,  150,  148,    0,  148,  144,
      148,  148,  148,    0,  142,  147,  151,  152,  151,  152,
      154,    0,  154,  153,  146,  153,  145,    0,  150,  149,
      158,  156,  158,  156,  155,  153,  155,  147,  160,  157,
      160,  157,    0,  151,  152,  153,  161,  155,  161,    0,
      158,  149,  156,  162,  153,  162,  160,  159,  153,  159,
      163,  167,  163,  167,    0,  151,  152,  157,  153,  159,
      155,    0,  164,  158,  164,  156,  153,    0,    0,  160,
      166,  165,  166,  165,  168,  169,  168,  169,    0,  157,

      164,    0,  159,  165,  166,  170,  172,  170,  172,  173,
      174,  173,  174,    0,  176,  177,  176,  177,  168,  169,
      172,    0,  175,  164,  175,    0,  165,  166,  176,  181,
      173,  181,  170,  183,  184,  183,  184,  182,  174,  182,
        0,  168,  169,  172,  177,  185,  186,  185,  186,    0,
      175,  176,  181,  173,  170,  182,  184,  187,  185,  187,
      174,  183,    0,  188,  186,  188,  177,  189,  190,  189,
      190,    0,  175,  188,  191,  181,  191,    0,  182,  184,
      192,  185,  192,  183,  193,    0,  193,  186,    0,  195,
      194,  195,  194,  196,    0,  196,  188,  197,    0,  197,

      193,  198,  199,  198,  199,  200,  201,  200,  201,  202,
        0,  202,  192,  194,  203,  197,  203,  195,  196,  204,
      205,  204,  205,  193,    0,  202,  206,  207,  206,  207,
      198,  199,    0,    0,  192,  205,  194,  204,  197,  195,
      208,  196,  208,    0,  209,  207,  209,    0,  202,  210,
        0,  210,  198,  199,  212,  206,  212,  211,  205,  211,
      204,  213,  214,  213,  214,  209,    0,  210,  207,    0,
      215,  211,  215,    0,    0,  213,  214,  206,  212,  216,
        0,  216,  217,  218,  217,  218,    0,  219,  209,  219,
      210,    0,    0,  215,  211,  217,  218,    0,  213,  214,

        0,  212,  216,  220,  221,  220,  221,  222,    0,  222,
        0,    0,    0,    0,    0,    0,  215,    0,  217,  218,
        0,    0,    0,    0,    0,  216,  224,  224,  224,  225,
      225,  225,  226,    0,  226,  227,    0,  227,  229,    0,
      229,  230,    0,  230,  231,    0,  231,  233,    0,  233,
      234,    0,  234,  236,    0,  236,  237,    0,  237,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,

      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  223,  223,
      223,  223,  223,  223
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int pp_flex_debug;
int pp_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *pptext;
#line 1 "pplex.l"
/*							-*- c -*-
   Copyright (C) 2001,2002,2003,2004,2005,2006,2007 Keisuke Nishida
   Copyright (C) 2007-2009 Roger While

   This file is part of GNU Cobol.

   The GNU Cobol compiler is free software; you can redistribute it
   and/or modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2 of the
   License, or (at your option) any later version.

   GNU Cobol is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with GNU Cobol; see the file COPYING. If not, write to
   the Free Software Foundation, 51 Franklin Street, Fifth Floor,
   Boston, MA 02110-1301 USA
*/
#line 31 "pplex.l"

#include "config.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef	HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <ctype.h>
#include <errno.h>
#include <sys/stat.h>
#include <sys/types.h>

#include "cobc.h"
#include "ppparse.h"

static char	*plexbuff1 = NULL;
static char	*plexbuff2 = NULL;
static struct list_files *old_list_file = NULL;
static size_t	newline_count = 0;
static size_t	within_comment = 0;
static size_t	inside_bracket = 0;
static size_t	consecutive_quotation = 0;
static int	quotation_mark = 0;
static int	last_line_1 = -1;
static int	last_line_2 = -1;

static struct cb_replace_list	*current_replace_list = NULL;

static struct cb_text_list	*text_queue = NULL;

static struct copy_info {
	struct copy_info	*next;
	struct list_files	*listfile;
	char			*file;
	int			line;
	int			replacing;
	int			quotation_mark;
	YY_BUFFER_STATE		buffer;
} *copy_stack = NULL;

#define YY_INPUT(buf,result,max_size) result = ppinput (buf, max_size);

static int ppinput (char *buf, int max_size);
static void ppecho (const char *text);

static void switch_to_buffer (const int lineno, const char *filename,
			      YY_BUFFER_STATE buffer);


#line 850 "pplex.c"

#define INITIAL 0
#define PROCESS_STATE 1
#define COPY_STATE 2
#define PSEUDO_STATE 3

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int pplex_destroy (void );

int ppget_debug (void );

void ppset_debug (int debug_flag  );

YY_EXTRA_TYPE ppget_extra (void );

void ppset_extra (YY_EXTRA_TYPE user_defined  );

FILE *ppget_in (void );

void ppset_in  (FILE * in_str  );

FILE *ppget_out (void );

void ppset_out  (FILE * out_str  );

yy_size_t ppget_leng (void );

char *ppget_text (void );

int ppget_lineno (void );

void ppset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int ppwrap (void );
#else
extern int ppwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( pptext, ppleng, 1, ppout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( ppin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( ppin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, ppin))==0 && ferror(ppin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(ppin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int pplex (void);

#define YY_DECL int pplex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after pptext and ppleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 89 "pplex.l"





#line 1033 "pplex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! ppin )
			ppin = stdin;

		if ( ! ppout )
			ppout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			ppensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				pp_create_buffer(ppin,YY_BUF_SIZE );
		}

		pp_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of pptext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 224 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 223 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 94 "pplex.l"
{
	ppecho (" ");
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 98 "pplex.l"
{ BEGIN PROCESS_STATE; }
	YY_BREAK

case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 101 "pplex.l"
{ BEGIN INITIAL; unput ('\n'); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 102 "pplex.l"
{ cb_warning (_("PROCESS statement is ignored")); }
	YY_BREAK

case 5:
YY_RULE_SETUP
#line 105 "pplex.l"
{
	struct list_files *newfile;
	BEGIN COPY_STATE;
	newfile = cobc_malloc (sizeof (struct list_files));
	memset (newfile, 0, sizeof (struct list_files));
	newfile->copy_line = cb_source_line;
	if (cb_current_file->copy_tail) {
		cb_current_file->copy_tail->next = newfile;
	}
	if (!cb_current_file->copy_head) {
		cb_current_file->copy_head = newfile;
	}
	cb_current_file->copy_tail = newfile;
	old_list_file = cb_current_file;
	cb_current_file = newfile;
	return COPY;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 122 "pplex.l"
{ BEGIN COPY_STATE; return COPY; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 123 "pplex.l"
{ BEGIN COPY_STATE; return REPLACE; }
	YY_BREAK

case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 126 "pplex.l"
{ ECHO; cb_source_line++; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 127 "pplex.l"
{ /* ignore */ }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 128 "pplex.l"
{ BEGIN INITIAL; return '.'; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 129 "pplex.l"
{ BEGIN PSEUDO_STATE; return EQEQ; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 130 "pplex.l"
{ return '('; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 131 "pplex.l"
{ return ')'; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 132 "pplex.l"
{ return BY; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 133 "pplex.l"
{ return IN; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 134 "pplex.l"
{ return OF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 135 "pplex.l"
{ return OFF; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 136 "pplex.l"
{ return SUPPRESS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 137 "pplex.l"
{ return PRINTING; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 138 "pplex.l"
{ return REPLACING; }
	YY_BREAK
case 21:
#line 140 "pplex.l"
case 22:
#line 141 "pplex.l"
case 23:
#line 142 "pplex.l"
case 24:
YY_RULE_SETUP
#line 142 "pplex.l"
{ pplval.s = strdup (pptext); return TOKEN; }
	YY_BREAK


case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 146 "pplex.l"
{ ECHO; cb_source_line++; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 147 "pplex.l"
{ pplval.s = strdup (" "); return TOKEN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 148 "pplex.l"
{ BEGIN COPY_STATE; return EQEQ; }
	YY_BREAK
case 28:
#line 150 "pplex.l"
case 29:
#line 151 "pplex.l"
case 30:
#line 152 "pplex.l"
case 31:
YY_RULE_SETUP
#line 152 "pplex.l"
{ pplval.s = strdup (pptext); return TOKEN; }
	YY_BREAK

case 32:
#line 156 "pplex.l"
case 33:
#line 157 "pplex.l"
case 34:
#line 158 "pplex.l"
case 35:
#line 159 "pplex.l"
case 36:
#line 160 "pplex.l"
case 37:
#line 161 "pplex.l"
case 38:
YY_RULE_SETUP
#line 161 "pplex.l"
{
	/* these words are treated as comments */
	if (cb_verify (cb_author_paragraph, pptext)) {
		/* skip comments until the end of line */
		int c;

		within_comment = 1;
		while ((c = input ()) != EOF) {
			if (c == '\n') {
				break;
			}
		}
		unput (c);
	}
}
	YY_BREAK
case 39:
#line 178 "pplex.l"
case 40:
#line 179 "pplex.l"
case 41:
#line 180 "pplex.l"
case 42:
YY_RULE_SETUP
#line 180 "pplex.l"
{
	/* these words are comments in IBM COBOL */
	if (cb_verify (cb_eject_statement, pptext)) {
		/* do nothing for now */
	} else {
		ECHO;
	}
}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 189 "pplex.l"
{ ppecho ("\n"); cb_source_line++; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 191 "pplex.l"
{ ppecho (" "); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 193 "pplex.l"
{
	if (inside_bracket) {
		ppecho (", ");
	} else {
		ppecho (" ");
	}
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 201 "pplex.l"
{
	inside_bracket++;
	ppecho ("(");
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 206 "pplex.l"
{
	if (inside_bracket) {
		inside_bracket--;
	}
	ppecho (")");
}
	YY_BREAK
case 48:
#line 214 "pplex.l"
case 49:
#line 215 "pplex.l"
case 50:
#line 216 "pplex.l"
case 51:
YY_RULE_SETUP
#line 216 "pplex.l"
{ ppecho (pptext); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PROCESS_STATE):
case YY_STATE_EOF(COPY_STATE):
case YY_STATE_EOF(PSEUDO_STATE):
#line 218 "pplex.l"
{
	struct copy_info *p;

	p = copy_stack;

	pp_delete_buffer (YY_CURRENT_BUFFER);

	/* Terminate at the end of all input */
	if (p->next == NULL) {
		within_comment = 0;
		newline_count = 0;
		inside_bracket = 0;
		current_replace_list = NULL;
		text_queue = NULL;
		copy_stack = NULL;
		quotation_mark = 0;
		consecutive_quotation = 0;
		last_line_1 = -1;
		last_line_2 = -1;
		yyterminate ();
	}

	/* Close the current file */
	fclose (ppin);

	/* Switch to the last buffer */
	if (p->replacing) {
		pp_set_replace_list (NULL);
	}
	if (p->listfile) {
	   cb_current_file = p->listfile;
	}
	switch_to_buffer (p->line, p->file, p->buffer);
	quotation_mark = p->quotation_mark;

	copy_stack = p->next;
	free (p);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 257 "pplex.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1425 "pplex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed ppin at a new source and called
			 * pplex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = ppin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( ppwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * pptext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of pplex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					pprealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			pprestart(ppin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) pprealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 224 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 224 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 223);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up pptext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					pprestart(ppin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( ppwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve pptext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void pprestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        ppensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            pp_create_buffer(ppin,YY_BUF_SIZE );
	}

	pp_init_buffer(YY_CURRENT_BUFFER,input_file );
	pp_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void pp_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		pppop_buffer_state();
	 *		pppush_buffer_state(new_buffer);
     */
	ppensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	pp_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (ppwrap()) processing, but the only time this flag
	 * is looked at is after ppwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void pp_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	ppin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE pp_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) ppalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pp_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) ppalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in pp_create_buffer()" );

	b->yy_is_our_buffer = 1;

	pp_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with pp_create_buffer()
 * 
 */
    void pp_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		ppfree((void *) b->yy_ch_buf  );

	ppfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a pprestart() or at EOF.
 */
    static void pp_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	pp_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then pp_init_buffer was _probably_
     * called from pprestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void pp_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		pp_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void pppush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	ppensure_buffer_stack();

	/* This block is copied from pp_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from pp_switch_to_buffer. */
	pp_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void pppop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	pp_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		pp_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void ppensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)ppalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ppensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)pprealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ppensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE pp_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) ppalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pp_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	pp_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to pplex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       pp_scan_bytes() instead.
 */
YY_BUFFER_STATE pp_scan_string (yyconst char * yystr )
{
    
	return pp_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to pplex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE pp_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) ppalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in pp_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = pp_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in pp_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up pptext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		pptext[ppleng] = (yy_hold_char); \
		(yy_c_buf_p) = pptext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		ppleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int ppget_lineno  (void)
{
        
    return pplineno;
}

/** Get the input stream.
 * 
 */
FILE *ppget_in  (void)
{
        return ppin;
}

/** Get the output stream.
 * 
 */
FILE *ppget_out  (void)
{
        return ppout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t ppget_leng  (void)
{
        return ppleng;
}

/** Get the current token.
 * 
 */

char *ppget_text  (void)
{
        return pptext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void ppset_lineno (int  line_number )
{
    
    pplineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see pp_switch_to_buffer
 */
void ppset_in (FILE *  in_str )
{
        ppin = in_str ;
}

void ppset_out (FILE *  out_str )
{
        ppout = out_str ;
}

int ppget_debug  (void)
{
        return pp_flex_debug;
}

void ppset_debug (int  bdebug )
{
        pp_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from pplex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    ppin = stdin;
    ppout = stdout;
#else
    ppin = (FILE *) 0;
    ppout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * pplex_init()
     */
    return 0;
}

/* pplex_destroy is for both reentrant and non-reentrant scanners. */
int pplex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		pp_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		pppop_buffer_state();
	}

	/* Destroy the stack itself. */
	ppfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * pplex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *ppalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *pprealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void ppfree (void * ptr )
{
	free( (char *) ptr );	/* see pprealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 257 "pplex.l"



void
pp_set_replace_list (struct cb_replace_list *list)
{
	current_replace_list = list;
	if (list && cb_listing_file) {

	   struct cb_replace_list *r;
	   struct cb_text_list	*l;

	   for (r = list; r; r = r->next) {
	      struct list_replace *repl;

	      repl = cobc_malloc (sizeof (struct list_replace));
	      memset (repl, 0, sizeof (struct list_replace));
	      repl->firstline = r->line_num;
	      repl->lastline = cb_source_line;
	      for (l = r->old_text; l; l = l->next) 
		 strcat (repl->from, l->text);
	      for (l = r->new_text; l; l = l->next) 
		 strcat (repl->to, l->text);
	      
	      if (cb_current_file->replace_tail) {
		 cb_current_file->replace_tail->next = repl;
	      }
	      if (!cb_current_file->replace_head) {
		 cb_current_file->replace_head = repl;
	      }
	      cb_current_file->replace_tail = repl;
	   }
	}
}

static void
switch_to_buffer (const int line, const char *file, YY_BUFFER_STATE buffer)
{
	char	*p;

	cb_source_line = line;
	cb_source_file = strdup (file);
	for (p = cb_source_file; *p; p++) {
		if (*p == '\\') {
			*p = '/';
		}
	}
	pp_switch_to_buffer (buffer);
	fprintf (ppout, "# %d \"%s\"\n", line, cb_source_file);
}

int
ppopen (const char *name, struct cb_replace_list *replace_list)
{
	struct copy_info *p;

	for (; newline_count > 0; newline_count--) {
		ungetc ('\n', ppin);
	}

	/* Open the copy file */
	ppin = fopen (name, "rb");
	if (!ppin) {
		if (cb_source_file) {
			cb_error (_("%s: %s"), name, strerror (errno));
		} else {
			perror (name);
		}
		return -1;
	}

	strcpy (cb_current_file->name, name);

	/* Add to dependency list */
	if (cb_depend_file) {
		cb_depend_list = cb_text_list_add (cb_depend_list, name);
	}

	/* Preserve the current buffer */
	p = cobc_malloc (sizeof (struct copy_info));
	p->line = cb_source_line;
	p->file = cb_source_file;
	p->replacing = replace_list ? 1 : 0;
	p->buffer = YY_CURRENT_BUFFER;
	p->quotation_mark = quotation_mark;
	p->next = copy_stack;
	p->listfile = old_list_file;
	copy_stack = p;
	cb_current_file->copy_line = cb_source_line;

	/* Switch to new buffer */
	if (replace_list) {
		pp_set_replace_list (replace_list);
	}
	switch_to_buffer (1, name, pp_create_buffer (ppin, YY_BUF_SIZE));
	return 0;
}

int
ppcopy (const char *name, const char *lib, struct cb_replace_list *replace_list)
{
	struct cb_text_list	*il;
	struct cb_text_list	*el;
	char			*s;
	struct stat		st;

	cb_current_file->copy_line = cb_source_line;
	if (lib) {
		if (!plexbuff1) {
			plexbuff1 = cobc_malloc (COB_SMALL_BUFF);
		}
		snprintf (plexbuff1, COB_SMALL_MAX, "%s/%s", lib, name);
		s = plexbuff1;
	} else {
		s = (char *)name;
	}

	/* Find the file */
	if (stat (s, &st) == 0) {
		return ppopen (s, replace_list);
	}
	if (!plexbuff2) {
		plexbuff2 = cobc_malloc (COB_SMALL_BUFF);
	}
	for (el = cb_extension_list; el; el = el->next) {
		snprintf (plexbuff2, COB_SMALL_MAX, "%s%s", s, el->text);
		if (stat (plexbuff2, &st) == 0) {
			return ppopen (plexbuff2, replace_list);
		}
	}
	if (*s != '/') {
		for (il = cb_include_list; il; il = il->next) {
			for (el = cb_extension_list; el; el = el->next) {
				snprintf (plexbuff2, COB_SMALL_MAX, "%s/%s%s",
					  il->text, name, el->text);
				if (stat (plexbuff2, &st) == 0) {
					return ppopen (plexbuff2, replace_list);
				}
			}
		}
	}
	cb_error (_("%s: %s"), name, strerror (errno));
	return -1;
}

/* Check directives */
/* This is horrible but we have to parse directives directly after the read */
/* as flex buffers up input and it is then too late to use the flex parser */

static void
check_directive (char *buff, int *line_size)
{
	char	*s;
	char	*dirptr;
	size_t	cnt;
	int	n;
	char	sbuff[5][256];

	if (cb_source_format == CB_FORMAT_FIXED) {
		if (*line_size < 8) {
			return;
		}
		if (buff[6] != ' ') {
			return;
		}
		s = &buff[7];
	} else {
		s = buff;
	}
	for (; *s == ' '; s++) {
		;
	}
	dirptr = s;
	if (*s != '>') {
		return;
	}
	s++;
	if (*s != '>') {
		return;
	}
	s++;
	if (*s == 'D') {
		if (cb_flag_debugging_line) {
			memset (dirptr, ' ', 3);
		} else {
			for (cnt = 0; cnt < newline_count; cnt++) {
				buff[cnt] = '\n';
			}
			buff[cnt] = 0;
			strcat (buff, "      *> DEBUG\n");
			*line_size = strlen (buff);
			newline_count = 0;
		}
		return;
	}
	if (!strncasecmp (s, "PAGE", 4)) {
		for (cnt = 0; cnt < newline_count; cnt++) {
			buff[cnt] = '\n';
		}
		buff[cnt] = 0;
		strcat (buff, "      *> PAGE\n");
		*line_size = strlen (buff);
		newline_count = 0;
		return;
	}
	memset (sbuff[0], 0, sizeof (sbuff));
	n = sscanf (s, "%255s %255s %255s %255s %255s",
			sbuff[0], sbuff[1], sbuff[2], sbuff[3], sbuff[4]);
	for (cnt = 0; cnt < newline_count; cnt++) {
		buff[cnt] = '\n';
	}
	buff[cnt] = 0;
	newline_count = 0;
	strcat (buff, "      *> DIRECTIVE\n");
	*line_size = strlen (buff);
	if (n < 2 || strcasecmp (sbuff[0], "SOURCE")) {
		cb_warning (_("Invalid directive - ignored"));
		return;
	}
	switch (n) {
	case 2:
		if (!strcasecmp (sbuff[1], "FIXED")) {
			cb_source_format = CB_FORMAT_FIXED;
			return;
		}
		if (!strcasecmp (sbuff[1], "FREE")) {
			cb_source_format = CB_FORMAT_FREE;
			return;
		}
		break;
	case 3:
		if (strcasecmp (sbuff[1], "FORMAT") &&
		    strcasecmp (sbuff[1], "IS")) {
			break;
		}
		if (!strcasecmp (sbuff[2], "FIXED")) {
			cb_source_format = CB_FORMAT_FIXED;
			return;
		}
		if (!strcasecmp (sbuff[2], "FREE")) {
			cb_source_format = CB_FORMAT_FREE;
			return;
		}
		break;
	default:
		if (strcasecmp (sbuff[1], "FORMAT")) {
			break;
		}
		if (strcasecmp (sbuff[2], "IS")) {
			break;
		}
		if (!strcasecmp (sbuff[3], "FIXED")) {
			cb_source_format = CB_FORMAT_FIXED;
			return;
		}
		if (!strcasecmp (sbuff[3], "FREE")) {
			cb_source_format = CB_FORMAT_FREE;
			return;
		}
		break;
	}
	cb_warning (_("Invalid directive - ignored"));
}

/*
 * Read line
 */

static int
ppinput (char *buff, int max_size)
{

	char	*bp;
	size_t	gotcr;
	size_t	continuation = 0;
	int	ipchar;
	int	i;
	int	n;
	int	coln;

start:
	/* read a line */
	gotcr = 0;
	ipchar = 0;
	for (n = 0; n < 256 && ipchar != '\n';) {
		ipchar = getc (ppin);
		if (ipchar == EOF) {
			if (newline_count == 0) {
				return 0;
			}
			memset (buff, '\n', newline_count);
			buff[newline_count] = 0;
			newline_count = 0;
			return strlen (buff);
		}
		/*
		if (n == 0 && cb_source_format != CB_FORMAT_FIXED) {
			if (ipchar != ' ' && ipchar != '\n') {
				buff[n++] = ' ';
			}
		}
		*/
		if (gotcr) {
			if (ipchar != '\n') {
				buff[n++] = '\r';
			}
			gotcr = 0;
		}
		if (ipchar == '\r') {
			gotcr = 1;
		} else if (ipchar == '\t') {
			buff[n++] = ' ';
			while (n % cb_tab_width != 0) {
				buff[n++] = ' ';
			}
		} else {
			buff[n++] = ipchar;
		}
	}

	if (buff[n - 1] != '\n') {
		cb_warning (_("Line not terminated by a newline"));
		buff[n++] = '\n';
	}
	buff[n] = 0;

	check_directive (buff, &n);

	/* nothing more to do with free format */
	if (cb_source_format != CB_FORMAT_FIXED) {
		if (buff[0] == '*' || buff[0] == '/') {
			newline_count++;
			goto start;
		}
		return n;
	}

	/* line too short */
	if (n < 8) {
		newline_count++;
		goto start;
	}

	if (cb_flag_mfcomment) {
		if (buff[0] == '*' || buff[0] == '/') {
			newline_count++;
			goto start;
		}
	}
	/* check the indicator (column 7) */
	bp = buff + 7;
	switch (buff[6]) {
	case ' ':
		break;
	case '-':
		continuation = 1;
		break;
	case 'd':
	case 'D':
		/* debugging line */
		if (cb_flag_debugging_line) {
			break;
		}
		newline_count++;
		goto start;
	case '*':
	case '/':
		/* comment line */
		newline_count++;
		goto start;
	default:
		/* invalid indicator */
		cb_error (_("Invalid indicator '%c' at column 7"), buff[6]);
		return YY_NULL;
	}

	/* skip comments that follow after AUTHORS, etc. */
	if (within_comment) {
		/* Check all of "Area A" */
		switch (n) {
		case 8:
			if (buff[7] == ' ') {
				newline_count++;
				goto start;
			}
			break;
		case 9:
			if (!memcmp (&buff[7], "  ", 2)) {
				newline_count++;
				goto start;
			}
			break;
		case 10:
			if (!memcmp (&buff[7], "   ", 3)) {
				newline_count++;
				goto start;
			}
			break;
		default:
			if (!memcmp (&buff[7], "    ", 4)) {
				newline_count++;
				goto start;
			}
			break;
		}
		within_comment = 0;
	}

	/* check the text that is longer than cb_text_column */
	if (n > cb_text_column + 1) {

		/* show warning if it is not whitespaces */
		if (cb_warn_column_overflow && last_line_2 < cb_source_line - 1) {
			for (coln = cb_text_column; coln < n; coln++) {
				if (buff[coln] != ' ' && buff[coln] != '\n') {
					cb_warning (_("Source text after column %d"),
						    cb_text_column);
					break;
				}
			}
		}

		/* remove it */
		strcpy (buff + cb_text_column, "\n");
		last_line_2 = cb_source_line;
		n = cb_text_column + 1;
	}

	/* skip blank lines */
	for (i = 7; buff[i] == ' '; i++) ;
	if (buff[i] == '\n') {
		newline_count++;
		goto start;
	}

	if (continuation) {
		/* line continuation */
		for (; *bp == ' '; bp++) ;

		/* validate concatenation */
		if (consecutive_quotation) {
			if (bp[0] == quotation_mark && bp[1] == quotation_mark) {
				bp++;
			} else {
				cb_error (_("Invalid line continuation"));
				return YY_NULL;
			}
			quotation_mark = 0;
			consecutive_quotation = 0;
		} else if (quotation_mark) {
			/* literal concatenation */
			if (*bp == quotation_mark) {
				bp++;
			} else {
				cb_error (_("Invalid line continuation"));
				return YY_NULL;
			}
		}
	} else {
		/* normal line */
		quotation_mark = 0;
		consecutive_quotation = 0;
	}

	/* check if string literal is to be continued */
	for (i = bp - buff; buff[i] != '\n'; i++) {
		if (buff[i] == '\'' || buff[i] == '\"') {
			if (quotation_mark == 0) {
				/* literal start */
				quotation_mark = buff[i];
			} else if (quotation_mark == buff[i]) {
				if (i == cb_text_column - 1) {
					/* consecutive quotation */
					consecutive_quotation = 1;
				} else {
					/* literal end */
					quotation_mark = 0;
				}
			}
		}
	}

	/* truncate trailing spaces, including the newline */
	if (quotation_mark) {
		for (; i < 72;) {
			buff[i++] = ' ';
		}
		buff[i] = 0;
	} else {
		for (i--; buff[i] == ' '; i--) ;
		if (buff[i] == '\'' || buff[i] == '\"') {
			buff[++i] = ' ';
		}
		buff[i + 1] = 0;
	}

	if (continuation) {
		memmove (buff, bp, strlen (bp) + 1);
		newline_count++;
	} else {
		/* insert newlines at the start of the buffer */
		memmove (buff + newline_count, bp, strlen (bp) + 1);
		memset (buff, '\n', newline_count);
		newline_count = 1;
	}
	return strlen (buff);
}

static void
ppecho (const char *text)
{
	struct cb_replace_list	*r;
	struct cb_text_list	*l;
	struct cb_text_list	*queue;

	if (text_queue == NULL && (text[0] == ' ' || text[0] == '\n')) {
		fputs (text, ppout);
	} else if (!current_replace_list) {
		for (; text_queue; text_queue = text_queue->next) {
			fputs (text_queue->text, ppout);
		}
		fputs (text, ppout);
	} else {
		/* Do replacement */

		text_queue = cb_text_list_add (text_queue, text);

		for (r = current_replace_list; r; r = r->next) {
			queue = text_queue;
			for (l = r->old_text; l; l = l->next) {
				while (l && (l->text[0] == ' ' || l->text[0] == '\n')) {
					l = l->next;
				}
				if (l == NULL) {
					break;
				}
				while (queue && (queue->text[0] == ' ' ||
				       queue->text[0] == '\n')) {
					queue = queue->next;
				}
				if (queue == NULL) {
					return;	/* partial match */
				}
				if (strcasecmp (l->text, queue->text) != 0) {
					break;
				}
				queue = queue->next;
			}
			if (l == NULL) {
				/* match */
				for (l = r->new_text; l; l = l->next) {
				   fputs (l->text, ppout);
				}
/*
				text_queue = queue ? queue->next : NULL;
*/
				text_queue = queue;
				continue;
			}
		}

		/* no match */
		for (; text_queue; text_queue = text_queue->next) {
			fputs (text_queue->text, ppout);
		}
	}
}

