/* Generated by            cobc 2.0.20140120 */
/* Generated from          ../../debugger/gc-debugger.cob */
/* Generated at            Mai 12 2015 15:54:25 */
/* GNU Cobol build date    May 12 2015 15:43:59 */
/* GNU Cobol package date  Jan 20 2014 07:40:53 UTC */
/* Compile command         ..\Win32\Debug\cobc -C -frelax-syntax -I ..\..\debugger ..\..\debugger\gc-debugger.cob */

/* Program local variables for 'gc-debugger' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module initialization indicator */
static unsigned int	physical_cancel = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d0;
cob_decimal	*d1;


/* File bp-file */
static cob_file		*h_BP_FILE = NULL;
static unsigned char	h_BP_FILE_status[4];

/* File log-file */
static cob_file		*h_LOG_FILE = NULL;
static unsigned char	h_LOG_FILE_status[4];

/* LINKAGE SECTION items */


/* Screens */

static cob_screen	s_325;
static cob_screen	s_324;
static cob_screen	s_323;
static cob_screen	s_322;
static cob_screen	s_321;
static cob_screen	s_320;
static cob_screen	s_319;
static cob_screen	s_318;
static cob_screen	s_317;
static cob_screen	s_316;
static cob_screen	s_315;
static cob_screen	s_314;
static cob_screen	s_313;
static cob_screen	s_312;
static cob_screen	s_311;
static cob_screen	s_310;
static cob_screen	s_309;
static cob_screen	s_308;
static cob_screen	s_307;
static cob_screen	s_306;
static cob_screen	s_305;
static cob_screen	s_304;
static cob_screen	s_303;
static cob_screen	s_302;
static cob_screen	s_301;
static cob_screen	s_300;
static cob_screen	s_299;
static cob_screen	s_298;
static cob_screen	s_297;
static cob_screen	s_296;
static cob_screen	s_295;
static cob_screen	s_294;
static cob_screen	s_293;
static cob_screen	s_292;
static cob_screen	s_291;
static cob_screen	s_290;
static cob_screen	s_289;
static cob_screen	s_288;
static cob_screen	s_287;
static cob_screen	s_286;
static cob_screen	s_285;
static cob_screen	s_284;
static cob_screen	s_283;
static cob_screen	s_282;
static cob_screen	s_281;
static cob_screen	s_280;
static cob_screen	s_279;
static cob_screen	s_278;
static cob_screen	s_277;
static cob_screen	s_276;
static cob_screen	s_275;
static cob_screen	s_274;
static cob_screen	s_273;
static cob_screen	s_272;
static cob_screen	s_271;
static cob_screen	s_270;
static cob_screen	s_269;
static cob_screen	s_268;
static cob_screen	s_267;
static cob_screen	s_266;
static cob_screen	s_265;
static cob_screen	s_264;
static cob_screen	s_263;
static cob_screen	s_262;
static cob_screen	s_261;
static cob_screen	s_260;
static cob_screen	s_259;
static cob_screen	s_258;
static cob_screen	s_257;
static cob_screen	s_256;
static cob_screen	s_255;
static cob_screen	s_254;
static cob_screen	s_253;
static cob_screen	s_252;
static cob_screen	s_251;
static cob_screen	s_250;
static cob_screen	s_249;
static cob_screen	s_248;
static cob_screen	s_247;
static cob_screen	s_246;
static cob_screen	s_245;
static cob_screen	s_244;
static cob_screen	s_243;
static cob_screen	s_242;
static cob_screen	s_241;
static cob_screen	s_240;
static cob_screen	s_239;
static cob_screen	s_238;
static cob_screen	s_237;
static cob_screen	s_236;
static cob_screen	s_235;
static cob_screen	s_234;
static cob_screen	s_233;
static cob_screen	s_232;
static cob_screen	s_231;
static cob_screen	s_230;
static cob_screen	s_229;
static cob_screen	s_228;
static cob_screen	s_227;
static cob_screen	s_226;
static cob_screen	s_225;
static cob_screen	s_224;
static cob_screen	s_223;
static cob_screen	s_222;


/* Call pointers */
cob_call_union		cob_unifunc;

/* Subscripts */
int		i1;

/* Local cob_field items */
cob_field		f0;
cob_field		f1;


/* Call parameters */
cob_field		*cob_procedure_params[3];

/* Perform frame stack */
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int       b_1;	/* RETURN-CODE */
static cob_u8_t  b_6[40];	/* bp-file Record */
static cob_u8_t  b_8[512];	/* log-file Record */
static cob_u8_t  b_94[128];	/* GETLINE */
static cob_u8_t  b_95[128];	/* GETLINECOUNT */
static cob_u8_t  b_96[128];	/* ANIDATA */
static cob_u8_t  b_97[128];	/* STRINGCONTAINS */
static cob_u8_t  b_98[1];	/* global-init-flag */
static cob_u8_t  b_99[1];	/* module-init-flag */
static cob_u8_t  b_100[5];	/* active-line */
static cob_u8_t  b_101[2];	/* active-line-onscreen */
static cob_u8_t  b_102[6];	/* call-depth */
static cob_u8_t  b_103[6];	/* step-over-mode-counter */
static cob_u8_t  b_104[6];	/* step-over-return-depth */
static cob_u8_t  b_105[1];	/* run-mode */
static cob_u8_t  b_109[30];	/* step-over-module */
static cob_u8_t  b_110[1];	/* f6-hit */
static cob_u8_t  b_111[1];	/* cob-anim-logging */
static cob_u8_t  b_112[30];	/* cob-logging-module */
static cob_u8_t  b_113[1];	/* onscreen-mode */
static cob_u8_t  b_117[1];	/* continue-search-mode */
static cob_u8_t  b_120[2];	/* lines-set */
static cob_u8_t  b_121[4100];	/* codelines-data */
static cob_u8_t  b_125[2];	/* cobfile-status */
static cob_u8_t  b_126[256];	/* cobfile-path */
static cob_u8_t  b_127[2];	/* log-file-status */
static cob_u8_t  b_128[256];	/* log-file-path */
static cob_u8_t  b_129[10];	/* VV-NAME */
static cob_u8_t  b_130[10];	/* VV-USAGE */
static cob_u8_t  b_131[10];	/* VV-SIZE */
static cob_u8_t  b_132[10];	/* VV-CONTENT */
static cob_u8_t  b_133[2100];	/* EMPTYLINE */
static cob_u8_t  b_134[40];	/* SEARCH-SCREEN-HEADLINE */
static cob_u8_t  b_135[40];	/* SEARCH-SCREEN-MIDLINE */
static cob_u8_t  b_136[40];	/* SEARCH-SCREEN-MIDLINE-2 */
static cob_u8_t  b_137[40];	/* SEARCH-SCREEN-MIDLINE-3 */
static cob_u8_t  b_138[40];	/* SEARCH-LAST-SEARCH */
static cob_u8_t  b_142[2];	/* line-cursor-position */
static cob_u8_t  b_143[5];	/* module-line-count */
static cob_u8_t  b_144[5];	/* goto-linenumber */
static cob_u8_t  b_145[4];	/* inp-crt-status */
static cob_u8_t  b_146[70];	/* tmp-command-input-buffer */
static cob_u8_t  b_147[256];	/* tmp-unstring-buffer */
static cob_u8_t  b_148[3];	/* tmp-unstring-ptr */
static cob_u8_t  b_149[2];	/* tmp-line-position */
static cob_u8_t  b_150[512];	/* tmp-source-line-buffer */
static cob_u8_t  b_151[5];	/* tmp-linenumber */
static cob_u8_t  b_152[5];	/* tmp-linenumber-2 */
static cob_u8_t  b_153[5];	/* tmp-linenumber-3 */
static cob_u8_t  b_154[5];	/* tmp-number */
static cob_u8_t  b_155[5];	/* tmp-number-2 */
static cob_u8_t  b_156[2];	/* tmp-onscreen-linenumber */
static cob_u8_t  b_157[2];	/* tmp-onscreen-linenumber-2 */
static cob_u8_t  b_158[4];	/* tmp-linenumber-bin */
static cob_u8_t  b_159[5];	/* tmp-counter */
static cob_u8_t  b_160[30];	/* tmp-cobol-src-name */
static cob_u8_t  b_161[30];	/* tmp-bp-src-name */
static cob_u8_t  b_162[5];	/* tmp-bp-src-line */
static cob_u8_t  b_163[50];	/* tmp-wp-var-name */
static cob_u8_t  b_164[512];	/* tmp-log-line */
static cob_u8_t  b_165[1];	/* bp-wp-init-flag */
static cob_u8_t  b_166[5];	/* bp-next-line */
static cob_u8_t  b_167[5];	/* bp-delete-src-line */
static cob_u8_t  b_170[30];	/* bp-delete-src-name */
static cob_u8_t  b_173[1];	/* is-breakpoint-flag */
static cob_u8_t  b_174[40];	/* bp-wp-temp-record */
static cob_u8_t  b_175[258];	/* bp-file-info */
static cob_u8_t  b_178[4];	/* bp-line-counter */
static cob_u8_t  b_179[4];	/* bp-amount */
static cob_u8_t  b_180[35000];	/* breakpoint-lst */
static int       b_182;	/* bp-index */
static cob_u8_t  b_185[6400];	/* watchpoint-lst */
static cob_u8_t  b_191[346];	/* wp-interface-block */
static cob_u8_t  b_202[1];	/* watchpoint-changed-flag */
static cob_u8_t  b_203[1];	/* string-contains-flag */
static cob_u8_t  b_204[256];	/* string-contains-str1 */
static cob_u8_t  b_205[256];	/* string-contains-str2 */
static cob_u8_t  b_206[30];	/* search-string */
static cob_u8_t  b_207[30];	/* last-search-string */
static cob_u8_t  b_208[5];	/* search-result-line */
static cob_u8_t  b_209[5];	/* last-search-result-line */
static cob_u8_t  b_222[1777];	/* animator-screen */
static cob_u8_t  b_297[600];	/* view-variable-screen */
static cob_u8_t  b_315[2100];	/* empty-screen */
static cob_u8_t  b_317[320];	/* search-screen */
static cob_u8_t  b_326[4];	/* COB-CRT-STATUS */

/* End of data storage */


/* Fields */
static cob_field f_5	= {40, b_6 + 0, &a_1};	/* bp-line */
static cob_field f_6	= {40, b_6, &a_1};	/* bp-file Record */
static cob_field f_7	= {512, b_8 + 0, &a_1};	/* log-line */
static cob_field f_8	= {512, b_8, &a_1};	/* log-file Record */
static cob_field f_94	= {128, b_94, &a_1};	/* GETLINE */
static cob_field f_95	= {128, b_95, &a_1};	/* GETLINECOUNT */
static cob_field f_96	= {128, b_96, &a_1};	/* ANIDATA */
static cob_field f_97	= {128, b_97, &a_1};	/* STRINGCONTAINS */
static cob_field f_98	= {1, b_98, &a_3};	/* global-init-flag */
static cob_field f_99	= {1, b_99, &a_3};	/* module-init-flag */
static cob_field f_101	= {2, b_101, &a_2};	/* active-line-onscreen */
static cob_field f_102	= {6, b_102, &a_4};	/* call-depth */
static cob_field f_103	= {6, b_103, &a_4};	/* step-over-mode-counter */
static cob_field f_104	= {6, b_104, &a_4};	/* step-over-return-depth */
static cob_field f_111	= {1, b_111, &a_1};	/* cob-anim-logging */
static cob_field f_112	= {30, b_112, &a_1};	/* cob-logging-module */
static cob_field f_123	= {5, b_121 + 0, &a_5};	/* linenumber */
static cob_field f_124	= {77, b_121 + 5, &a_1};	/* sourceline */
static cob_field f_127	= {2, b_127, &a_2};	/* log-file-status */
static cob_field f_128	= {256, b_128, &a_1};	/* log-file-path */
static cob_field f_129	= {10, b_129, &a_1};	/* VV-NAME */
static cob_field f_130	= {10, b_130, &a_1};	/* VV-USAGE */
static cob_field f_131	= {10, b_131, &a_1};	/* VV-SIZE */
static cob_field f_132	= {10, b_132, &a_1};	/* VV-CONTENT */
static cob_field f_133	= {2100, b_133, &a_1};	/* EMPTYLINE */
static cob_field f_134	= {40, b_134, &a_1};	/* SEARCH-SCREEN-HEADLINE */
static cob_field f_135	= {40, b_135, &a_1};	/* SEARCH-SCREEN-MIDLINE */
static cob_field f_136	= {40, b_136, &a_1};	/* SEARCH-SCREEN-MIDLINE-2 */
static cob_field f_137	= {40, b_137, &a_1};	/* SEARCH-SCREEN-MIDLINE-3 */
static cob_field f_138	= {40, b_138, &a_6};	/* SEARCH-LAST-SEARCH */
static cob_field f_142	= {2, b_142, &a_2};	/* line-cursor-position */
static cob_field f_143	= {5, b_143, &a_5};	/* module-line-count */
static cob_field f_144	= {5, b_144, &a_5};	/* goto-linenumber */
static cob_field f_146	= {70, b_146, &a_1};	/* tmp-command-input-buffer */
static cob_field f_147	= {256, b_147, &a_1};	/* tmp-unstring-buffer */
static cob_field f_148	= {3, b_148, &a_8};	/* tmp-unstring-ptr */
static cob_field f_149	= {2, b_149, &a_2};	/* tmp-line-position */
static cob_field f_150	= {512, b_150, &a_1};	/* tmp-source-line-buffer */
static cob_field f_151	= {5, b_151, &a_5};	/* tmp-linenumber */
static cob_field f_152	= {5, b_152, &a_5};	/* tmp-linenumber-2 */
static cob_field f_153	= {5, b_153, &a_5};	/* tmp-linenumber-3 */
static cob_field f_154	= {5, b_154, &a_5};	/* tmp-number */
static cob_field f_156	= {2, b_156, &a_2};	/* tmp-onscreen-linenumber */
static cob_field f_157	= {2, b_157, &a_2};	/* tmp-onscreen-linenumber-2 */
static cob_field f_158	= {4, b_158, &a_7};	/* tmp-linenumber-bin */
static cob_field f_159	= {5, b_159, &a_5};	/* tmp-counter */
static cob_field f_161	= {30, b_161, &a_1};	/* tmp-bp-src-name */
static cob_field f_162	= {5, b_162, &a_5};	/* tmp-bp-src-line */
static cob_field f_163	= {50, b_163, &a_1};	/* tmp-wp-var-name */
static cob_field f_164	= {512, b_164, &a_1};	/* tmp-log-line */
static cob_field f_166	= {5, b_166, &a_5};	/* bp-next-line */
static cob_field f_168	= {5, b_167 + 0, &a_5};	/* bp-check-src-line */
static cob_field f_170	= {30, b_170, &a_1};	/* bp-delete-src-name */
static cob_field f_171	= {30, b_170 + 0, &a_1};	/* bp-check-src-name */
static cob_field f_173	= {1, b_173, &a_3};	/* is-breakpoint-flag */
static cob_field f_174	= {40, b_174, &a_1};	/* bp-wp-temp-record */
static cob_field f_176	= {256, b_175 + 0, &a_1};	/* bp-path */
static cob_field f_177	= {2, b_175 + 256, &a_2};	/* bp-file-status */
static cob_field f_178	= {4, b_178, &a_9};	/* bp-line-counter */
static cob_field f_179	= {4, b_179, &a_9};	/* bp-amount */
static cob_field f_181	= {35, b_180 + 0, &a_6};	/* bp-line-struct */
static cob_field f_183	= {30, b_180 + 0, &a_1};	/* bp-src-name */
static cob_field f_184	= {5, b_180 + 30, &a_5};	/* bp-src-line */
static cob_field f_187	= {50, b_185 + 0, &a_1};	/* wp-var-name */
static cob_field f_188	= {30, b_185 + 50, &a_1};	/* wp-module */
static cob_field f_189	= {280, b_185 + 80, &a_1};	/* wp-value */
static cob_field f_190	= {280, b_185 + 360, &a_1};	/* last-wp-value */
static cob_field f_191	= {346, b_191, &a_6};	/* wp-interface-block */
static cob_field f_203	= {1, b_203, &a_3};	/* string-contains-flag */
static cob_field f_204	= {256, b_204, &a_1};	/* string-contains-str1 */
static cob_field f_205	= {256, b_205, &a_1};	/* string-contains-str2 */
static cob_field f_206	= {30, b_206, &a_1};	/* search-string */
static cob_field f_207	= {30, b_207, &a_1};	/* last-search-string */
static cob_field f_208	= {5, b_208, &a_5};	/* search-result-line */
static cob_field f_209	= {5, b_209, &a_5};	/* last-search-result-line */
static cob_field f_210	= {346, NULL, &a_6};	/* interface-block */
static cob_field f_211	= {1, NULL, &a_1};	/* anim-state */
static cob_field f_212	= {30, NULL, &a_1};	/* cobol-src-name */
static cob_field f_213	= {6, NULL, &a_4};	/* first-stmt-if */
static cob_field f_214	= {6, NULL, &a_4};	/* current-line-if */
static cob_field f_215	= {6, NULL, &a_4};	/* active-line-if */
static cob_field f_216	= {6, NULL, &a_4};	/* no-code-lines-if */
static cob_field f_217	= {6, NULL, &a_4};	/* dtf-line */
static cob_field f_218	= {2, NULL, &a_2};	/* dtf-usage */
static cob_field f_219	= {3, NULL, &a_8};	/* dtf-length */
static cob_field f_220	= {280, NULL, &a_1};	/* dtf-value */
static cob_field f_221	= {1, NULL, &a_1};	/* anim-stmt-type */
static cob_field f_222	= {1777, b_222, &a_6};	/* animator-screen */
static cob_field f_223	= {60, b_222 + 0, &a_1};	/* headline */
static cob_field f_226	= {5, b_222 + 60, &a_5};	/* Implicit FILLER */
static cob_field f_227	= {74, b_222 + 65, &a_1};	/* Implicit FILLER */
static cob_field f_229	= {5, b_222 + 139, &a_5};	/* Implicit FILLER */
static cob_field f_230	= {74, b_222 + 144, &a_1};	/* Implicit FILLER */
static cob_field f_232	= {5, b_222 + 218, &a_5};	/* Implicit FILLER */
static cob_field f_233	= {74, b_222 + 223, &a_1};	/* Implicit FILLER */
static cob_field f_235	= {5, b_222 + 297, &a_5};	/* Implicit FILLER */
static cob_field f_236	= {74, b_222 + 302, &a_1};	/* Implicit FILLER */
static cob_field f_238	= {5, b_222 + 376, &a_5};	/* Implicit FILLER */
static cob_field f_239	= {74, b_222 + 381, &a_1};	/* Implicit FILLER */
static cob_field f_241	= {5, b_222 + 455, &a_5};	/* Implicit FILLER */
static cob_field f_242	= {74, b_222 + 460, &a_1};	/* Implicit FILLER */
static cob_field f_244	= {5, b_222 + 534, &a_5};	/* Implicit FILLER */
static cob_field f_245	= {74, b_222 + 539, &a_1};	/* Implicit FILLER */
static cob_field f_247	= {5, b_222 + 613, &a_5};	/* Implicit FILLER */
static cob_field f_248	= {74, b_222 + 618, &a_1};	/* Implicit FILLER */
static cob_field f_250	= {5, b_222 + 692, &a_5};	/* Implicit FILLER */
static cob_field f_251	= {74, b_222 + 697, &a_1};	/* Implicit FILLER */
static cob_field f_253	= {5, b_222 + 771, &a_5};	/* Implicit FILLER */
static cob_field f_254	= {74, b_222 + 776, &a_1};	/* Implicit FILLER */
static cob_field f_256	= {5, b_222 + 850, &a_5};	/* Implicit FILLER */
static cob_field f_257	= {74, b_222 + 855, &a_1};	/* Implicit FILLER */
static cob_field f_259	= {5, b_222 + 929, &a_5};	/* Implicit FILLER */
static cob_field f_260	= {74, b_222 + 934, &a_1};	/* Implicit FILLER */
static cob_field f_262	= {5, b_222 + 1008, &a_5};	/* Implicit FILLER */
static cob_field f_263	= {74, b_222 + 1013, &a_1};	/* Implicit FILLER */
static cob_field f_265	= {5, b_222 + 1087, &a_5};	/* Implicit FILLER */
static cob_field f_266	= {74, b_222 + 1092, &a_1};	/* Implicit FILLER */
static cob_field f_268	= {5, b_222 + 1166, &a_5};	/* Implicit FILLER */
static cob_field f_269	= {74, b_222 + 1171, &a_1};	/* Implicit FILLER */
static cob_field f_271	= {5, b_222 + 1245, &a_5};	/* Implicit FILLER */
static cob_field f_272	= {74, b_222 + 1250, &a_1};	/* Implicit FILLER */
static cob_field f_274	= {5, b_222 + 1324, &a_5};	/* Implicit FILLER */
static cob_field f_275	= {74, b_222 + 1329, &a_1};	/* Implicit FILLER */
static cob_field f_277	= {5, b_222 + 1403, &a_5};	/* Implicit FILLER */
static cob_field f_278	= {74, b_222 + 1408, &a_1};	/* Implicit FILLER */
static cob_field f_280	= {5, b_222 + 1482, &a_5};	/* Implicit FILLER */
static cob_field f_281	= {74, b_222 + 1487, &a_1};	/* Implicit FILLER */
static cob_field f_282	= {1, b_222 + 1561, &a_1};	/* line-cursor */
static cob_field f_283	= {80, b_222 + 1562, &a_1};	/* status-line */
static cob_field f_284	= {50, b_222 + 1642, &a_1};	/* command-input-line */
static cob_field f_285	= {75, b_222 + 1692, &a_6};	/* footline */
static cob_field f_286	= {15, b_222 + 1692, &a_1};	/* func1 */
static cob_field f_287	= {15, b_222 + 1707, &a_1};	/* func2 */
static cob_field f_288	= {15, b_222 + 1722, &a_1};	/* func3 */
static cob_field f_289	= {15, b_222 + 1737, &a_1};	/* func4 */
static cob_field f_290	= {15, b_222 + 1752, &a_1};	/* func5 */
static cob_field f_291	= {10, b_222 + 1767, &a_6};	/* footline-2 */
static cob_field f_292	= {2, b_222 + 1767, &a_1};	/* func1-2 */
static cob_field f_293	= {2, b_222 + 1769, &a_1};	/* func2-2 */
static cob_field f_294	= {2, b_222 + 1771, &a_1};	/* func3-2 */
static cob_field f_295	= {2, b_222 + 1773, &a_1};	/* func4-2 */
static cob_field f_296	= {2, b_222 + 1775, &a_1};	/* func5-2 */
static cob_field f_297	= {600, b_297, &a_6};	/* view-variable-screen */
static cob_field f_298	= {80, b_297 + 0, &a_1};	/* headline-vv */
static cob_field f_300	= {10, b_297 + 80, &a_1};	/* name-vv-head */
static cob_field f_301	= {60, b_297 + 90, &a_1};	/* name-vv-content */
static cob_field f_303	= {10, b_297 + 150, &a_1};	/* usage-vv-head */
static cob_field f_304	= {60, b_297 + 160, &a_1};	/* usage-vv-content */
static cob_field f_306	= {10, b_297 + 220, &a_1};	/* size-vv-head */
static cob_field f_307	= {60, b_297 + 230, &a_1};	/* size-vv-content */
static cob_field f_309	= {10, b_297 + 290, &a_1};	/* content-vv-head */
static cob_field f_310	= {60, b_297 + 300, &a_1};	/* content-vv-l1 */
static cob_field f_311	= {60, b_297 + 360, &a_1};	/* content-vv-l2 */
static cob_field f_312	= {60, b_297 + 420, &a_1};	/* content-vv-l3 */
static cob_field f_313	= {60, b_297 + 480, &a_1};	/* content-vv-l4 */
static cob_field f_314	= {60, b_297 + 540, &a_1};	/* content-vv-l5 */
static cob_field f_315	= {2100, b_315, &a_6};	/* empty-screen */
static cob_field f_316	= {2100, b_315 + 0, &a_1};	/* Implicit FILLER */
static cob_field f_317	= {320, b_317, &a_6};	/* search-screen */
static cob_field f_318	= {40, b_317 + 0, &a_1};	/* Implicit FILLER */
static cob_field f_319	= {40, b_317 + 40, &a_1};	/* Implicit FILLER */
static cob_field f_320	= {40, b_317 + 80, &a_1};	/* Implicit FILLER */
static cob_field f_321	= {40, b_317 + 120, &a_1};	/* Implicit FILLER */
static cob_field f_322	= {40, b_317 + 160, &a_1};	/* Implicit FILLER */
static cob_field f_323	= {40, b_317 + 200, &a_1};	/* Implicit FILLER */
static cob_field f_324	= {40, b_317 + 240, &a_1};	/* Implicit FILLER */
static cob_field f_325	= {40, b_317 + 280, &a_1};	/* Implicit FILLER */
static cob_field f_326	= {4, b_326, &a_9};	/* COB-CRT-STATUS */

/* End of fields */

