/* Generated by            cobc 2.0.20140120 */
/* Generated from          ../../debugger/gc-debugger.cob */
/* Generated at            Mai 12 2015 15:54:25 */
/* GNU Cobol build date    May 12 2015 15:43:59 */
/* GNU Cobol package date  Jan 20 2014 07:40:53 UTC */
/* Compile command         ..\Win32\Debug\cobc -C -frelax-syntax -I ..\..\debugger ..\..\debugger\gc-debugger.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x10,   2,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   1,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x10,   6,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x10,   5,   0, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_7 =	{0x11,   9,   0, 0x0041, NULL};
static const cob_field_attr a_8 =	{0x10,   3,   0, 0x0000, NULL};
static const cob_field_attr a_9 =	{0x10,   4,   0, 0x0000, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* End of fields */


/* Constants */
static const cob_field c_1	= {2, (cob_u8_ptr)"23", &a_2};
static const cob_field c_2	= {2, (cob_u8_ptr)"10", &a_2};
static const cob_field c_3	= {19, (cob_u8_ptr)"Do-Initialization, ", &a_1};
static const cob_field c_4	= {18, (cob_u8_ptr)"global-init-flag: ", &a_1};
static const cob_field c_5	= {20, (cob_u8_ptr)", module-init-flag: ", &a_1};
static const cob_field c_6	= {14, (cob_u8_ptr)", call-depth: ", &a_1};
static const cob_field c_7	= {21, (cob_u8_ptr)"COB_SCREEN_EXCEPTIONS", &a_1};
static const cob_field c_8	= {1, (cob_u8_ptr)"Y", &a_1};
static const cob_field c_9	= {14, (cob_u8_ptr)"COB_SCREEN_ESC", &a_1};
static const cob_field c_10	= {16, (cob_u8_ptr)"COB_ANIM_LOGGING", &a_1};
static const cob_field c_11	= {18, (cob_u8_ptr)"COB_LOGGING_MODULE", &a_1};
static const cob_field c_12	= {1, (cob_u8_ptr)"1", &a_3};
static const cob_field c_13	= {9, (cob_u8_ptr)"Command: ", &a_1};
static const cob_field c_14	= {12, (cob_u8_ptr)"get_aniline_", &a_1};
static const cob_field c_15	= {14, (cob_u8_ptr)"get_linecount_", &a_1};
static const cob_field c_16	= {8, (cob_u8_ptr)"anidata_", &a_1};
static const cob_field c_17	= {28, (cob_u8_ptr)"GNU COBOL 2.0 Debugger  --  ", &a_1};
static const cob_field c_18	= {19, (cob_u8_ptr)"Normal mode step...", &a_1};
static const cob_field c_19	= {19, (cob_u8_ptr)"Set GO-MODE to true", &a_1};
static const cob_field c_20	= {15, (cob_u8_ptr)"Go mode step...", &a_1};
static const cob_field c_21	= {18, (cob_u8_ptr)"Checked for BP... ", &a_1};
static const cob_field c_22	= {2, (cob_u8_ptr)"; ", &a_1};
static const cob_field c_23	= {1, (cob_u8_ptr)";", &a_1};
static const cob_field c_24	= {16, (cob_u8_ptr)"No BP, goback...", &a_1};
static const cob_field c_25	= {20, (cob_u8_ptr)"Perform/Call step...", &a_1};
static const cob_field c_26	= {1, (cob_u8_ptr)"7", &a_3};
static const cob_field c_27	= {1, (cob_u8_ptr)"2", &a_3};
static const cob_field c_28	= {1, (cob_u8_ptr)"6", &a_3};
static const cob_field c_29	= {33, (cob_u8_ptr)"Möchten sie den Debugger beenden\?", &a_1};
static const cob_field c_30	= {1, (cob_u8_ptr)"J", &a_1};
static const cob_field c_31	= {30, (cob_u8_ptr)"saved step-over-return-depth: ", &a_1};
static const cob_field c_32	= {1, (cob_u8_ptr)" ", &a_1};
static const cob_field c_33	= {33, (cob_u8_ptr)"goto-line, line-cursor-position: ", &a_1};
static const cob_field c_34	= {2, (cob_u8_ptr)"19", &a_2};
static const cob_field c_35	= {19, (cob_u8_ptr)"COB_BREAKPOINT_FILE", &a_1};
static const cob_field c_36	= {20, (cob_u8_ptr)"xanim_breakpoint.lst", &a_1};
static const cob_field c_37	= {13, (cob_u8_ptr)"Empty bp list", &a_1};
static const cob_field c_38	= {3, (cob_u8_ptr)"L!;", &a_1};
static const cob_field c_39	= {1, (cob_u8_ptr)"4", &a_3};
static const cob_field c_40	= {26, (cob_u8_ptr)"**************************", &a_1};
static const cob_field c_41	= {25, (cob_u8_ptr)"*************************", &a_1};
static const cob_field c_42	= {1, (cob_u8_ptr)"G", &a_1};
static const cob_field c_43	= {25, (cob_u8_ptr)"After calling animdata...", &a_1};
static const cob_field c_44	= {3, (cob_u8_ptr)"all", &a_1};
static const cob_field c_45	= {12, (cob_u8_ptr)"anim-state: ", &a_1};
static const cob_field c_46	= {16, (cob_u8_ptr)"cobol-src-name: ", &a_1};
static const cob_field c_47	= {15, (cob_u8_ptr)"first-stmt-if: ", &a_1};
static const cob_field c_48	= {17, (cob_u8_ptr)"current-line-if: ", &a_1};
static const cob_field c_49	= {16, (cob_u8_ptr)"active-line-if: ", &a_1};
static const cob_field c_50	= {18, (cob_u8_ptr)"no-code-lines-if: ", &a_1};
static const cob_field c_51	= {10, (cob_u8_ptr)"dtf-line: ", &a_1};
static const cob_field c_52	= {11, (cob_u8_ptr)"dtf-usage: ", &a_1};
static const cob_field c_53	= {12, (cob_u8_ptr)"dtf-length: ", &a_1};
static const cob_field c_54	= {11, (cob_u8_ptr)"dtf-value: ", &a_1};
static const cob_field c_55	= {16, (cob_u8_ptr)"anim-stmt-type: ", &a_1};
static const cob_field c_56	= {20, (cob_u8_ptr)"check for stop run. ", &a_1};
static const cob_field c_57	= {2, (cob_u8_ptr)", ", &a_1};
static const cob_field c_58	= {9, (cob_u8_ptr)"STOP RUN.", &a_1};
static const cob_field c_59	= {36, (cob_u8_ptr)"check for perform or call statement.", &a_1};
static const cob_field c_60	= {4, (cob_u8_ptr)"CALL", &a_1};
static const cob_field c_61	= {7, (cob_u8_ptr)"PERFORM", &a_1};
static const cob_field c_62	= {2, (cob_u8_ptr)"14", &a_2};
static const cob_field c_63	= {3, (cob_u8_ptr)"del", &a_1};
static const cob_field c_64	= {20, (cob_u8_ptr)"Watchpoint value of ", &a_1};
static const cob_field c_65	= {14, (cob_u8_ptr)" changed from ", &a_1};
static const cob_field c_66	= {4, (cob_u8_ptr)" to ", &a_1};
static const cob_field c_67	= {17, (cob_u8_ptr)"Added watchpoint ", &a_1};
static const cob_field c_68	= {41, (cob_u8_ptr)"No more watchpoints possible. (limit: 10)", &a_1};
static const cob_field c_69	= {24, (cob_u8_ptr)"Deleted all watchpoints.", &a_1};
static const cob_field c_70	= {1, (cob_u8_ptr)"0", &a_3};
static const cob_field c_71	= {1, (cob_u8_ptr)"3", &a_3};
static const cob_field c_72	= {1, (cob_u8_ptr)"5", &a_3};
static const cob_field c_73	= {1, (cob_u8_ptr)"8", &a_3};
static const cob_field c_74	= {1, (cob_u8_ptr)"9", &a_3};
static const cob_field c_75	= {2, (cob_u8_ptr)"11", &a_2};
static const cob_field c_76	= {2, (cob_u8_ptr)"12", &a_2};
static const cob_field c_77	= {2, (cob_u8_ptr)"13", &a_2};
static const cob_field c_78	= {2, (cob_u8_ptr)"15", &a_2};
static const cob_field c_79	= {2, (cob_u8_ptr)"16", &a_2};
static const cob_field c_80	= {2, (cob_u8_ptr)"17", &a_2};
static const cob_field c_81	= {2, (cob_u8_ptr)"18", &a_2};
static const cob_field c_82	= {2, (cob_u8_ptr)"20", &a_2};
static const cob_field c_83	= {2, (cob_u8_ptr)"22", &a_2};
static const cob_field c_84	= {2, (cob_u8_ptr)"25", &a_2};
static const cob_field c_85	= {2, (cob_u8_ptr)"33", &a_2};
static const cob_field c_86	= {2, (cob_u8_ptr)"49", &a_2};
static const cob_field c_87	= {2, (cob_u8_ptr)"65", &a_2};
static const cob_field c_88	= {2, (cob_u8_ptr)"24", &a_2};

static cob_field cob_all_low	= {1, (cob_u8_ptr)"\0", &cob_all_attr};
static cob_field cob_all_space	= {1, (cob_u8_ptr)" ", &cob_all_attr};

static void COB_NOINLINE
cob_set_screen (cob_screen *s, cob_screen *next,
		cob_screen *child, cob_field *field, cob_field *value,
		cob_field *line, cob_field *column,
		cob_field *foreg, cob_field *backg, cob_field *prompt,
		const int type, const int occurs, const int attr)
{
	s->next = next;
	s->child = child;
	s->field = field;
	s->value = value;
	s->line = line;
	s->column = column;
	s->foreg = foreg;
	s->backg = backg;
	s->prompt = prompt;
	s->type = type;
	s->occurs = occurs;
	s->attr = attr;
}

static int COB_NOINLINE
cob_get_numdisp (const void *data, const size_t size)
{
	const unsigned char	*p;
	size_t			n;
	int    			 retval;
	p = (const unsigned char *)data;
	retval = 0;
	for (n = 0; n < size; ++n, ++p) {
		retval *= 10;
		retval += (*p & 0x0F);
	}
	return retval;
}

